behaviors:
  bachelor:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120
      buffer_size: 20480
      learning_rate: 3e-5
      beta: 5.0e-3
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.93
      num_epoch: 9
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      conditioning_type: hyper
      memory:
        use_recurrent: true
        memory_size: 128
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 64
    summary_freq: 10000 #50000
    threaded: true
environment_parameters:
  levelDifficulty:
    curriculum:
      - name: firstLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: bachelor
          signal_smoothing: true
          min_lesson_length: 420 # Number of episodes that have to exceed the defined threshold
          threshold: 2 # The defined threshold
        value: 0
      - name: secondLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: bachelor
          signal_smoothing: true
          min_lesson_length: 420 
          threshold: 2 
        value: 1
      - name: thirdLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: bachelor
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 2
        value: 2
      - name: fourthLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: bachelor
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 2
        value: 3
      - name: fifthLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: bachelor
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 2
        value: 4
      - name: sixthLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: bachelor
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 2
        value: 5
      - name: seventhLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: bachelor
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 4
        value: 6
      - name: eighthLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: bachelor
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 7
        value: 7
      - name: ninethLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: bachelor
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 9
        value: 8
      - name: tenthLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: bachelor
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 11
        value: 9
      - name: eleventhLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: bachelor
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 13
        value: 10
      - name: twelvthLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: bachelor
          signal_smoothing: true
          min_lesson_length: 420
          threshold: 15
        value: 11